# Generated by Django 3.2.10 on 2024-09-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
